import BpmnModeler from "bpmn-js/lib/Modeler";
import minimapModule from "diagram-js-minimap";
import { BpmnPropertiesPanelModule, BpmnPropertiesProviderModule } from "bpmn-js-properties-panel";
import camundaModdleDescriptor from "camunda-bpmn-moddle/resources/camunda.json";
import { layoutProcess } from "bpmn-auto-layout";
import { CreateAppendAnythingModule, CreateAppendElementTemplatesModule } from "bpmn-js-create-append-anything";
import TokenSimulationModule from "bpmn-js-token-simulation";
import bpmnlintModule from "bpmn-js-bpmnlint";
import { recommendedLintConfig } from "./lib/bpmnlint-static-config";
import { ElementTemplatesPropertiesProviderModule } from "bpmn-js-element-templates";
import ElementTemplateChooserModule from "@bpmn-io/element-template-chooser";
import ElementTemplateIconRendererModule from "@bpmn-io/element-template-icon-renderer";
import camundaWithIconModdle from "./lib/camunda-with-icon-moddle";
import { ElementTemplatesExtendModule } from "./lib/element-templates-extend";

window.BpmnModeler = BpmnModeler;
window.BpmnJS = BpmnModeler;
window.minimapModule = minimapModule;
window.BpmnPropertiesPanelModule = BpmnPropertiesPanelModule;
window.BpmnPropertiesProviderModule = BpmnPropertiesProviderModule;
window.camundaModdleDescriptor = camundaModdleDescriptor;
window.AutoLayout = { layoutProcess };
window.CreateAppendAnythingModule = CreateAppendAnythingModule;
window.CreateAppendElementTemplatesModule = CreateAppendElementTemplatesModule;
window.TokenSimulationModule = TokenSimulationModule;
window.BpmnlintModule = bpmnlintModule;
window.BpmnlintRecommendedConfig = recommendedLintConfig;
window.ElementTemplatesPropertiesProviderModule = ElementTemplatesPropertiesProviderModule;
window.ElementTemplateChooserModule = ElementTemplateChooserModule;
window.ElementTemplateIconRendererModule = ElementTemplateIconRendererModule;
window.ElementTemplatesExtendModule = ElementTemplatesExtendModule;
window.camundaWithIconModdle = camundaWithIconModdle;
